### ISSUE TITLE
TypeError: stormpy.storage.storage.ChoiceLabeling: No constructor defined!

### ISSUE THREAD

**Issue by netro505** [moves-rwth/stormpy#104]
Hi! I'm still very new with Stormpy. I'm not sure if this is an issue on my part or Storm but I was following the Stormpy documentation specifically the Markov decision processes (MDPs) section and I stumble into this error. Again, I wasn't sure what's the problem here. Probably some of you could help me out.

![Screenshot 2022-11-03 195354](https://user-images.githubusercontent.com/74126496/199714116-f90d2dcf-3243-4137-b888-a144942c6b4c.jpg)

**Comment by volkm** [comment]
Hi, happy to hear that you are using stormpy.
I could not reproduce the error on my machine at the moment. Can you give a bit more details how your setup looks like?
I guess you followed [this code](https://moves-rwth.github.io/stormpy/doc/models/building_mdps.html)? How did you run the Notebook? Did you use the Binder image, a Docker container or did you build stormpy yourself? Which version of Storm and stormpy are you using?

**Comment by netro505** [comment]
Sorry, I should've been more specific. I run my Jupyter Notebook using a Docker container (following the previous Storm tutorial given in the three part tutorial video). I'm trying to learn [MDP in the Stormpy documentation](https://moves-rwth.github.io/stormpy/doc/models/building_mdps.html). Currently I am using Stormpy 1.6.0. 

![Screenshot 2022-11-04 015948](https://user-images.githubusercontent.com/74126496/199799296-51daa1f0-6cc2-432e-8c97-9a6a4111bf70.jpg)

Here are some of the files I'm using which is based on the Storm tutorial video

![Screenshot 2022-11-04 015709](https://user-images.githubusercontent.com/74126496/199798783-b39b06c7-a895-4337-9e46-f05c8a2097f4.jpg)

**Comment by volkm** [comment]
There were some changes between stormpy 1.6 (which you are using) and the latest version 1.7 (on which the examples are based on). I recommend to use the latest stormpy version to avoid any problems.

You can try to change the first line of the [Dockerfile](https://github.com/moves-rwth/stormpyter/blob/master/tutorial_discotec2020/Dockerfile#L1) to `FROM movesrwth/stormpy:1.7.0` and then [manually build the Dockerfile](https://github.com/moves-rwth/stormpyter/tree/master/tutorial_discotec2020#manual-build).
Another possibility is to use the Docker container from the [UAI tutorial](https://github.com/moves-rwth/stormpyter/tree/master/tutorial_uai#installation-steps) which is already using the latest Storm version.

**Comment by netro505** [comment]
Sorry for the late response. I'm now able to run the MDP tutorial thanks to you. I'm closing it now.
