### ISSUE TITLE
Building sparse parametric model fails

### ISSUE THREAD

**Issue by lukearcus** [moves-rwth/stormpy#136]
I'm running into an issue with the most recent version of stormpy when attempting to load a parametric model from a prism file.
The code I'm running is:
```
path = model_file
    prism_program = stormpy.parse_prism_program(path)
    print("\nBuilding model from {}".format(path))
    with open(property_file) as f:
        formula_str= " ".join([l.rstrip() for l in f])

    # Load properties
    properties = stormpy.parse_properties_for_prism_program(formula_str,
                                                            prism_program)

    # Set model options
    options = stormpy.BuilderOptions([p.raw_formula for p in properties])
    options.set_add_out_of_bounds_state()

    model = stormpy.build_sparse_parametric_model_with_options(prism_program,
                                                               options)

```

I end up with the following error:
```
ERROR (BitVectorHashMap.cpp:163): Size of bit vector and size of buckets do not match
python: /home/luke_test/install/storm/src/storm/storage/BitVectorHashMap.cpp:163: std::pair<bool, long unsigned int> storm::storage::BitVectorHashMap<ValueType, Hash>::findBucket(const storm::storage::BitVector&) const [with ValueType = unsigned int; Hash = storm::storage::Murmur3BitVectorHash<unsigned int>]: Assertion `key.size() == bucketSize' failed.
```

I've tried alternatively running
```
    properties = stormpy.parse_properties(formula_str, prism_program)

    model = stormpy.build_sparse_parametric_model(prism_program, properties)
```
which produces a different error:
```
ERROR (BitVector.cpp:561): Integer value (18446744073709551615) too large to fit in the given number of bits (4).
python: /home/luke_test/install/storm/src/storm/storage/BitVector.cpp:561: void storm::storage::BitVector::setFromInt(uint_fast64_t, uint_fast64_t, uint64_t): Assertion `numberOfBits == 64 || (value >> numberOfBit
s) == 0' failed.
```

Here are the relevant model definition files
[drone.zip](https://github.com/moves-rwth/stormpy/files/12929927/drone.zip)

I'm running with stormpy 1.8.0, storm 1.8.1.

The code worked in 1.6.4, and I am able to run the example code for parametric model .

**Comment by lukearcus** [comment]
The issues seems to be with this line:
```
    options.set_add_out_of_bounds_state()
```
Removing that the code runs for other model files I have, although still not the one attached

**Comment by volkm** [comment]
After a quick look it seems that your model file contains assignments such as `x'=x-2` which yield negative values. Adapting `formula valid` such that `2 <= x & x <= MAXX-2` solves this issue.

P.S. In line 2861, I think it should be `MAXXZ` instead of `MAXXZ`.

**Comment by lukearcus** [comment]
Fantastic, thank you! I think in previous versions this was being taken care of by the out-of-bounds state I suppose, is set_add_out_of_bounds now deprecated?

**Comment by volkm** [comment]
There was actually a bug for the out-of-bounds flag (see https://github.com/moves-rwth/storm/pull/417). After the merge in Storm it should work in stormpy as expected.

**Comment by lukearcus** [comment]
Fantastic, many thanks!
