### ISSUE TITLE
dd-to-sparse engine

### ISSUE THREAD

**Issue by temunds** [moves-rwth/stormpy#157]
Hello everyone,

i am trying to do some model-checking with the dd-to-sparse engine, mainly because of its capability to apply bisimulation to markov automata (see https://github.com/moves-rwth/storm/issues/498).

Is there a way to utilize this engine in stormpy, i could only find documentation and model-checking methods for other engines (https://moves-rwth.github.io/stormpy/doc/engines.html)?

Thank you and best regards :)

**Comment by tquatmann** [comment]
You can have the same effect by building the model symbolically first and then invoke [perform_symbolic_bisimulation](https://moves-rwth.github.io/stormpy/api/core.html#stormpy.perform_symbolic_bisimulation) with `quotient_format=stormpy.QuotientFormat.SPARSE`.
From there, you get a sparse model that you can model check as usual.
[This](https://github.com/moves-rwth/stormpy/blob/8ab412153ea5f37545cdc4e635757d23223b3092/tests/core/test_bisimulation.py#L42) test might serve as a reference.

**Comment by temunds** [comment]
Thanks, that does work.

However, implementing this, I faced the challenge that i am utilizing a prism model which has to be converted into a jani model. This does work for timed reachability properties by calling the `.to_jani()` method to the prism program.

In my prism model file, however, I define some reward structures. Trying to build the symbolic model throws the error:
`ERROR (Model.cpp:822): Cannot find unknown reward model 'waiting_re_0'.`

It seems like those rewards are not carried over to the jani model.

For reference, this is the relevant code fragment:

```
prism_program = stormpy.parse_prism_program(path_to_model)
prism_program = stormpy.preprocess_symbolic_input(prism_program, [], const_str)[0].as_prism_program()
properties = stormpy.parse_properties_for_prism_program(properties, prism_program)
jani_model, properties = prism_program.to_jani(properties)

#this might be unneccessary but I wanted to try this
properties = stormpy.parse_properties_for_jani_model('R{"waiting_re_0"}min=? [F "started_label_re_0"]', jani_model)

# the error is thrown in the next line
model = stormpy.build_symbolic_model(jani_model, properties=properties)
```

**Comment by tquatmann** [comment]
The `to_jani` method only converts rewards that occur in one of the given properties. What is `properties` before executing the following line?

```python
properties = stormpy.parse_properties_for_prism_program(properties, prism_program)
```

Do you get the same error without the `parse_properties_for_jani_model` step?

**Comment by temunds** [comment]
Thanks for your prompt response.

Sorry, `properties` is defined earlier to the same string:

```
properties = 'R{"waiting_re_0"}min=? [F "started_label_re_0"]'
```

The error is the same with and without the line
```
properties = stormpy.parse_properties_for_jani_model('R{"waiting_re_0"}min=? [F "started_label_re_0"]', jani_model)
```

EDIT: I can provide the model file in private if needed.

**Comment by tquatmann** [comment]
Yes, please send us the model at support@stormchecker.org. I cannot see any issue in your stormpy code right now.

**Comment by temunds** [comment]
While preparing the files for the transfer via mail, i checked the path of the model file - and discovered that an old version without the mentioned reward has been used 🤦

I am very sorry for the caused inconvenience.

Thank you for the support!
