### ISSUE TITLE
Failing tests on master branch

### ISSUE THREAD

**Issue by YouGuessedMyName** [moves-rwth/stormpy#167]
Two unit tests fail when running `python3 setup.py test`

![image](https://github.com/moves-rwth/stormpy/assets/50511564/66af9a4b-1a6f-4a27-acb6-674c8900283b)

**Comment by volkm** [comment]
Thanks for letting us know.
These errors stem from an issue in Storm (see https://github.com/moves-rwth/storm/issues/559) and should work again if the issue in Storm is fixed.
You can ignore these tests for now.
