### ISSUE TITLE
Matplotlib optional dependency

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/stormpy#72]
There is (very limited) functionality to support plotting in stormpy; which I like, but I dont want people to force installing matplotlib. Should we put this dependency into extras? It is also debatable whether CI should have a version with / without matplotlib?

**Comment by volkm** [comment]
Yes, I think we should have `plotting` in `extras` for users which want to have this functionality.

For testing, I think we should test two versions: one with all extras and the minimum version.

**Comment by volkm** [comment]
Closed with #73
