### ISSUE TITLE
Check Pybind version

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/stormpy#81]
Based on a discussion in https://github.com/moves-rwth/pycarl/pull/15#issuecomment-1202808495 we should check the PyBind11 version that pycarl uses and compare it to the one we are using for stormpy. While it may work without issue, at least providing a warning may be essential to prevent strange errors.

**Comment by volkm** [comment]
I fully agree.
The technical question is how to get the pybind version? While pybind has the variable `pybind11_VERSION` (see [here](https://pybind11.readthedocs.io/en/stable/cmake/index.html)), using `add_subdirectory` opens a new scope such that one cannot access this variable from outside.
One possibility might be to use `find_package` which needs an installation of pybind though.
Or we build a python function which accesses the version information available in `pybind11.h`. However, in that case the check can only be performed after compilation is finished.

**Comment by sjunges** [comment]
See also https://github.com/moves-rwth/stormpy/pull/86

**Comment by volkm** [comment]
The check was integrated by PR #86.
