### ISSUE TITLE
Parametric model checking for reward parameters

### ISSUE THREAD

**Issue by xinwei2124** [moves-rwth/stormpy#87]
Hi, there

It seems that the stormy 1.6.4 doesn't support the analysis of the DTMC models, whose state reward values are specified as parameters. Can you please confirm this. 

Best
Xinwei

**Comment by volkm** [comment]
Hi Xinwei,

stormpy **does support** the analysis of DTMCs with parametric rewards. Parametric models can be built similar to non-parametric ones, see [this code](https://github.com/moves-rwth/stormpy/blob/master/tests/pars/test_parametric.py#L64) for an example. The analysis approach then depends on what you want to compute. The simplest option is to compute the rational function representing the reward, see for example [this code](https://github.com/moves-rwth/stormpy/blob/master/tests/pars/test_parametric.py#L11) in the same file.

If you tell us a bit more what exactly you want to analyse, we can help in guiding you to the right approach.

Best,
Matthias

**Comment by xinwei2124** [comment]
Hi, Matthias

Thanks for your prompt reply. I looked into a bit and it is probably a bug in the code. 

I analysed a reachability reward property ( R{\"totalCost\"}=?[F s=5] ) of a simple pDTMC (attached in the email). 

It contains three parameters, they are p1, p2 and e1. 

The stormpy successfully returned the expression, which contains all three parameters, but the parameter e1 is missing from the returned variables. Please see the screenshot attached. 

 


Best
Xinwei

**Comment by volkm** [comment]
It seems that Github removes attachment when you reply by email. Can you upload your file(s) directly on Github? Then I will take a look at the issue.

**Comment by xinwei2124** [comment]
The model: [toy.txt](https://github.com/moves-rwth/stormpy/files/9462628/toy.txt)
The property: R{\"totalCost\"}=?[F s=5]

The screenshot: 
![Screenshot 2022-08-31 at 15 35 40](https://user-images.githubusercontent.com/62383976/187712589-22aba2d1-57b7-434a-8202-2c469b272dc4.png)

**Comment by volkm** [comment]
How did you obtain the list of parameters? Did you obtain them from the rational function or from the model? In the latter case, be sure to use `model.collect_all_parameters()`.

**Comment by xinwei2124** [comment]
Thanks for your help. I incorrectly used  model.collect_probability_parameters() to obtain the parameters.

**Comment by volkm** [comment]
I am happy to hear that this solves your problem.

For future reference: `collect_probability_parameters()` only collects the parameters on transitions, `collect_reward_parameters()` collects the parameters occurring in rewards, and `collect_all_parameters()` subsumes both and lists all parameters occurring in the model.
